version: "3.9"

services:
    # Application
    app:
        build:
            context: .
            dockerfile: _docker/app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - "database"
        networks:
            - web
            - internal
        container_name: ekst_app
        restart: always
    # Web Server
    ekst_server:
        build:
            context: .
            dockerfile: _docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./_docker/vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - "app"
        container_name: ekst_server
        restart: always
        labels:
            - "traefik.http.routers.ekst_server.rule=Host(`ekst.maximtresk.ru`)"
            - "traefik.port=80"
            - "traefik.docker.network=web"
            - "traefik.http.routers.ekst_server.entrypoints=websecure"
            - "traefik.http.routers.ekst_server.tls.certresolver=myresolver"
        networks:
            - web
            - internal
    # Database
    database:
        image: mysql:8.0
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "33063:3306"
        container_name: ekst_db
        restart: always
        networks:
            - internal
            - web
    # Database management
    pma:
        image: phpmyadmin:5.1
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_PORT=${DB_PORT}
        depends_on:
            - database
        ports:
            - "8887:80"
        networks:
            - web
            - internal
        container_name: ekst_pma
        restart: always

networks:
    web:
        external: true
    internal:
        external: false

volumes:
    dbdata:
